env:
  browser: true
  commonjs: true
  es6: true
extends:
  - 'eslint:recommended'
  - 'plugin:vue/essential'

parserOptions:
  sourceType: module
rules:
  vue/html-indent:
    - error
    - 2
  vue/script-indent:
    - error
    - o
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
